name: cassiopeia
description: naver kakao map location tracking app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  naver_map_plugin: ^0.9.5
  simple_throttle_debounce: ^1.0.3
  glass_kit: ^1.0.2
  page_transition: ^1.1.7+6
  video_player: ^2.0.2
  chewie: ^1.0.0
  scrollable_positioned_list: ^0.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
